Scanner
Teaching-projects/SOE-SZTA-2021-Tuti-a-moodle pull request #2
Opened 2021-02-21 10:01 UTC by Keelorath

Hi, létrehoztuk ezt a scanner branchet és dolgoztunk a "harc" fejlesztésén. Ránéznél légyszi, hogy minden oké-e?

2021-02-22 11:15 UTC, hegyhati requested changes
Par nem tul major dolog.

2021-02-22 11:15 UTC, hegyhati commented on Battle.java
> +    private final String player1Name;
Egy Entity valosiznuleg tudja magarol, hogy hivjak, ugyhogy az belemehetne magaba az osztalyba.

2021-02-22 11:15 UTC, hegyhati commented on Battle.java
> +            if (rand.nextBoolean()) {
igy minden korben random a sorrend. A keres nem ez volt, hanem az, hogy felvaltva ussek egymast. player 1 kezdjen.

2021-02-22 11:15 UTC, hegyhati commented on Battle.java
> +            printMessage("Unbalanced combat!");
Az "Unbalanced" szerintem nem a megfelelo szo itt.

2021-02-22 11:15 UTC, hegyhati commented on Battle.java
> +        if (player2.getAttack() <= player1.getDefense()) {
inkabb `else if`, jobban sugallja, hogy ez az ag csak akkor van, ha az elso nincs.

2021-02-22 11:15 UTC, hegyhati commented on Battle.java
> +    private void printLineOf(char character, int length) {
lehet akkor mar szemantikat is adnek a nevnek `printSeparator` vagy hasonlo.

2021-02-22 11:15 UTC, hegyhati commented on Battle.java
> +public class Battle {
A Java ilyen nyelv, hogy osztalyok nelkul nem nagyon letezhetnek fuggvenyek. De itt gyakorlatilag a konstruktorban beallitod a ket entity-t, aztan 1x lefuttathatod a csatat rajtuk. (Tobbszor nem, mert mar megurdelt az egyik ugye). Mas nyelveken erre az ember irna egy szimpla fuggvenyt. Java-ban ez nem opcio, de static fuggvenyeket tudsz csinalni, es itt szreintem indokoltabb is volna, ha minden fuggveny static volna, es a `battle` szimplan megkapna a ket Entity-t.

2021-02-22 11:15 UTC, hegyhati commented on Main.java
> +        bt.battle();
Tehat ez lehetne annyi, hogy `Battle.battle(good,evil)`, es akkor nincs feleslegesen letrehozva egy instance azert, hogy egyetlen egy fuggvenyet meghivjuk.

2021-02-22 11:15 UTC, hegyhati commented on Main.java
> +                value = Double.parseDouble(valueString);
miert nem hasznaljatok a `nextFloat`-ot inkabb?

2021-02-22 12:49 UTC, Keelorath commented on Battle.java
> +            printMessage("Unbalanced combat!");
Mit szólnál az "Unreasonable"-höz?

2021-02-22 18:14 UTC, hegyhati commented on Battle.java
> +            printMessage("Unbalanced combat!");
Ha nem limitaljuk magunkat egy szora, akar ki is irhatjuk, hogy olyan combat, amiben nem tortenik sebzes :-) 
De nyilvan nem ez volt a legkomolyabb komment, csak ez az eset pont hogy "balanced" :-)

2021-03-03 08:33 UTC, Keelorath commented
@hegyhati , esetleg ránéznél mégegyszer?

2021-03-03 21:01 UTC, hegyhati approved these changes

2021-03-03 21:02 UTC, merged